victoire_core:
    widgets:
        File:
            class: "Victoire\\Widget\\FileBundle\\Entity\\WidgetFile"
            name: File
            
jms_translation:
    configs:
        victoire_file_bundle:
            dirs: ["@VictoireFileBundle"]
            output_dir: "@VictoireFileBundle/Resources/translations"
