services:
    victoire_core.widget_file_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: File }
    #alias to the entity
    victoire.widget.file:
        class: Victoire\Widget\FileBundle\Entity\WidgetFile

    #alias to the form
    victoire.widget.form.file:
        class: Victoire\Widget\FileBundle\Form\WidgetFileType
        tags:
            - { name: form.type }
