services:
    victoire_core.twig.widget_file_manager:
        class: Victoire\FileBundle\Widget\Manager\WidgetFileManager
        arguments: [@service_container]

    widget_file_manager:
        alias: victoire_core.twig.widget_file_manager
